#!/bin/sh

# Shorthand script for `g++ <somefile.cpp> -std=c++11 -o somefile`
# 
# will break for file names that include dots as space delimiters
# e.g. some.file.cpp

infile=
outfile=
shouldrun=0

if [ "$1" == "run" ]; then
  infile=$2
  outfile=$3
  shouldrun=1
else
  infile=$1
  outfile=$2
fi

if [ "$outfile" == "" ]; then
  IFS=. read outfile afterdot <<< "${infile}"
  outfile="bin.${outfile}"
fi;

g++ $infile -std=c++11 -o $outfile
if [ $? -gt 0 ]; then
  exit;
fi

echo "Compiled '$infile' > '$outfile'"

if [ $shouldrun -eq 1 ]; then
  echo "Running '${outfile}'\n"
  "./${outfile}"
fi
