#!/bin/sh

# Shorthand script for `g++ <somefile.cpp> -std=c++11 -o somefile`
# 
# will break for file names that include dots as space delimiters
# e.g. some.file.cpp

if ["$2" == ""]
then
  IFS=. read outfile afterdot <<< "${1}"
else
  outfile = $2
fi

g++ $1 -std=c++11 -o $outfile
