#!/bin/sh

dirname=$1

if [ -d "$dirname" ]; then
  echo "Error: Directory '$dirname' already exists"
  exit 1
fi

mkdir "$dirname"
git clone https://github.com/photonstorm/phaser3-project-template.git "$dirname"
