#!/bin/sh
appname=$1
mkdir $appname
cd $appname
npm init -y
npm install react react-dom react-router --save
npm install webpack webpack-dev-server babel-core babel-loader babel-preset-es2015 babel-preset-react --save-dev
echo "{
  \"presets\": [
    \"es2015\",
    \"react\"
  ]
}" >> ".babelrc"
echo "module.exports = {
  entry: './app/main.js',
  output: {
    path: './app',
    filename: 'bundle.js',
  },
  devServer: {
    inline: true,
    contentBase: './app',
    port: 8100
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: '/node_modules/'
        loader: 'babel'
      }
    ]
  }
}" >> "webpack.config.js"
echo "/node_modules/*" >> ".gitignore"
git init
git add .
git commit -m "Initial commit"
cd ..
